name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PUPPETEER_SKIP_DOWNLOAD: 'true'
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: Install modules
              run: npm ci

            - name: Run ESLint
              run: npm run lint -- --report-unused-disable-directives

            - name: Run Jest
              run: npm test

            - name: Audit production dependencies
              run: npm audit --omit=dev
